name: 🚀 formbold react release

on:
  push:
    branches:
      - main # Adjust this to your desired branch

jobs:
  publish:
    name: 🚀 formbold react release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Clear npm cache
        run: npm cache clean --force
      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Replace with your build command if needed

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_FORMBOLDREACT }}
